# Project information
site_name: ubergoonz
site_author: ubergoonz
site_url: https://ubergoonz.github.io/docs-blog/
site_description: >-
  Documentation and blog by Ubergoonz

# Repository
repo_name: ubergoonz/docs-blog
repo_url: https://github/ubergoonz/docs-blog/

# Copyright
copyright: >
  Copyright &copy; 2025 Ubergoonz (Leslie Wang) <br>
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: lime
      accent: deep orange
#      text: white
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: lime
      accent: deep orange
#      text: black
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: lime
      accent: deep orange
#      text: white
  icon:
    logo: material/rocket-launch
    repo: material/github
  features:
    - navigation.expand
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - blog:
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_slugify_separator: _
      tags_slugify_format: "tag:{slug}"
  - search
  - meta

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/thumb-up-outline
        name: Yes - This page was helpful
        data: 1
        note: >-
          Thank you for your feedback! If you have any questions or
          suggestions, please feel free to reach out to us.
      - icon: material/thumb-down-outline
        name: No - This page could be improved
        data: 0
        note: >-
          Thank you for your feedback! If you have any questions or
          suggestions, please feel free to reach out to us.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  social:
    - icon: material/github
      link: https://github.com/ubergoonz/
    - icon: material/linkedin
      link: https://www.linkedin.com/in/ubergoonz/
    - icon: material/gitlab
      link: https://gitlab.com/ubergoonz/
  
extra_javascript:
  - assets/javascripts/consent.js

nav:
  - Home: index.md
  - Blog: blog/index.md