# Project information
site_name: the curious mind 🧠 of ubergoonz
site_url: https://ubergoonz.github.io/docs-blog/
site_author: ubergoonz
site_description: >-
  Documentation and blog by ubergoonz on technology, software development, AI Augmented Development and many more.
  <br>
  This website is intended for myself and any technologist who are keen to learn and share knowledge.

# Repository
repo_name: ubergoonz/docs-blog
repo_url: https://github.com/ubergoonz/docs-blog
edit_uri: edit/main/docs/

# Copyright
copyright: >-
  <script>
    document.getElementById('year').textContent = new Date().getFullYear();
  </script>
  <a href="about/copyright/">Copyright</a> &copy; 2025 - <span id="year"></span> <b>All Rights Reserved</b><br>
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep orange
      accent: lime
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: cyan
      accent: amber
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: indigo
      accent: lime
  favicon: assets/favicon.png
  logo: assets/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      copilot: octicons/copilot-16
      gitlab: simple/gitlab
      md: material/language-markdown-outline
      automation: material/auto-mode
      nix: octicons/terminal-16
      linux: simple/linux
      unix: octicons/terminal-16
      solaris: octicons/terminal-16
      plantuml: simple/uml
      vscode: material/microsoft-visual-studio-code
      docs: material/bookshelf
      materialmkdocs: simple/materialformkdocs
      ai-assisted-coding: material/robot-happy
      ai-augmented-development: material/robot-happy
      raspberrypi: simple/raspberrypi
    annotation: material/crosshairs-question
  font:
    text: Roboto
    code: Roboto Mono
  features:
#    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
#    - navigation.sections
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - announce.dismiss

plugins:
  - meta
  - blog:
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
      post_date_format: full
      blog_toc: false
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_url_format: "{slug}"
      post_url_date_format: yyyy/MM
      post_readtime_words_per_minute: 300
      archive: true
      archive_name: Archive
      archive_url_date_format: 
      archive_date_format: yyyy
      archive_toc: true
      categories: true
      categories_name: Categories
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_slugify_separator: _
      tags_slugify_format: "tag:{slug}"
      listings_map:
        custom-id:
          scope: false
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - macros
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        light: material/indigo-light
        dark: material/indigo-dark
      interaction:
        enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      locale: en
      timezone: UTC
      enable_git_follow: true
  - glightbox: # https://github.com/blueswen/mkdocs-glightbox#usage
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/thumb-up-outline
        name: Yes - This page was helpful
        data: 1
        note: >-
          Thank you for your feedback! If you have any questions or
          suggestions, please feel free to reach out to us.
      - icon: material/thumb-down-outline
        name: No - This page could be improved
        data: 0
        note: >-
          Thank you for your feedback! If you have any questions or
          suggestions, please feel free to reach out to us.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/ubergoonz/
    - icon: material/github
      link: https://github.com/ubergoonz/
    - icon: material/gitlab
      link: https://gitlab.com/ubergoonz/
  github_token: !ENV GITHUB_TOKEN
  blog:
    dir: blog
    author: Leslie Wang
    author_image: https://github.com/ubergoonz.png
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true
  tags:
    copilot: copilot
    gitlab: gitlab
    markdown: md
    automation: automation
    nix: nix
    linux: linux
    solaris: solaris
    unix: unix
    plantuml: plantuml
    vscode: vscode
    docs: docs
    materialmkdocs: materialmkdocs
    ai-assisted-coding: ai-assisted-coding
    ai-augmented-development: ai-augmented-development
    raspberrypi: raspberrypi
  status:
    deprecated: WIll be removed soon
    new: Recently added
    published: Page is complete an published
    hot: Hot topic
    draft: Draft - work in progress
extra_javascript:
  - assets/javascripts/consent.js

extra_css:
  - assets/stylesheets/extra.css

hooks:
  - overrides/hooks/socialmedia.py

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: ubergoonz
      repo: docs-blog
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"] # this is needed to make it easier to linking pathsrelative to the mkdocs root
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.caption:
nav:
  - Home: 
    - index.md
    - about/index.md
    - docs/index.md
    - blog/index.md
  - About:
    - about/index.md
    - Site Architecture: about/site-architecture.md
    - Site Navigation: about/site-navigation.md
    - Page Navigation: about/page-navigation.md
    - Page Style & Formatting: about/page-style-formatting.md
    - Page Status: 
        - about/page-status/index.md
        - about/page-status/deprecated.md
        - about/page-status/draft.md
        - about/page-status/hot.md
        - about/page-status/new.md
        - about/page-status/published.md
    - Copyright: about/copyright.md
    - Disclaimer: about/disclaimer.md
    - Changelog: about/changelog.md
    - Manual of Me: about/manual-of-me.md
  - Docs:
      - docs/index.md
      - Tags: docs/tags.md
      - Automations:
        - Overview: docs/automations/index.md
        - Explanation: docs/automations/explanation/index.md
        - How to: docs/automations/how-to/index.md
        - References: docs/automations/reference/index.md
        - Tutorials: docs/automations/tutorial/index.md
      - GitHub Copilot:
        - Overview: docs/github-copilot/index.md
        - Explanation: docs/github-copilot/explanation/index.md
        - How to: docs/github-copilot/how-to/index.md
        - References: docs/github-copilot/reference/index.md
        - Tutorials: docs/github-copilot/tutorial/index.md
      - Markdown:
        - Overview: docs/markdown/index.md
        - Explanation: docs/markdown/explanation/index.md
        - How to: docs/markdown/how-to/index.md
        - References: docs/markdown/reference/index.md
        - Tutorials: docs/markdown/tutorial/index.md
      - GitLab:
        - Overview: docs/gitlab/index.md
        - Explanation: docs/gitlab/explanation/index.md
        - How to: docs/gitlab/how-to/index.md
        - References: docs/gitlab/reference/index.md
        - Tutorials: docs/gitlab/tutorial/index.md
      - Material for MkDocs:
          - Overview: docs/material-mkdocs/index.md
          - Explanation: docs/material-mkdocs/explanation/index.md
          - How to: docs/material-mkdocs/how-to/index.md
          - References: docs/material-mkdocs/reference/index.md
          - Tutorials: docs/material-mkdocs/tutorial/index.md
      - "*nix": 
        - Overview: docs/nix/index.md
        - Explanation: 
          - docs/nix/explanation/index.md
          - docs/nix/explanation/my-unix-journey.md
        - How to: docs/nix/how-to/index.md
        - References: docs/nix/reference/index.md
        - Tutorials: docs/nix/tutorial/index.md
      - PlantUML: 
        - Overview: docs/plantuml/index.md
        - Explanation: docs/plantuml/explanation/index.md
        - How to: docs/plantuml/how-to/index.md
        - References: docs/plantuml/reference/index.md
        - Tutorials: docs/plantuml/tutorial/index.md
      - Visual Studio Code: 
        - Overview: docs/vscode/index.md
        - Explanation: docs/vscode/explanation/index.md
        - How to: docs/vscode/how-to/index.md
        - References: docs/vscode/reference/index.md
        - Tutorials: docs/vscode/tutorial/index.md
  - Blog:
      - blog/index.md
      - Tags: blog/tags.md