# Project information
site_name: ubergoonz
site_url: https://ubergoonz.github.io/docs-blog/
site_author: ubergoonz
site_description: >-
  Documentation and blog by ubergoonz on technology, software development, AI Augmented Development.

# Repository
repo_name: ubergoonz/docs-blog
repo_url: https://github.com/ubergoonz/docs-blog
edit_uri: edit/main/docs/

# Copyright
copyright: >
  <a href="about/copyright/">Copyright</a> &copy; 2025 - <script>document.write(new Date().getFullYear())</script> ubergoonz docs-blog <b>All Rights Reserved</b><br>
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep orange
      accent: lime
      scheme: slate
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: cyan
      accent: amber
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: indigo
      accent: pink
  favicon: assets/favicon.png
  logo: assets/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      copilot: octicons/copilot-16
      gitlab: simple/gitlab
      md: material/language-markdown-outline
      automation: material/auto-mode
      nix: octicons/terminal-16
      plantuml: simple/uml
      vscode: material/microsoft-visual-studio-code
  font:
    text: Roboto
    code: Roboto Mono

  features:
#    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
#    - navigation.sections
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - meta
  - blog:
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
      post_date_format: full
      blog_toc: false
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_url_format: "{slug}"
      post_url_date_format: yyyy/MM
      post_readtime_words_per_minute: 300
      archive: true
      archive_name: Archive
      archive_url_date_format: 
      archive_date_format: yyyy
      archive_toc: true
      categories: true
      categories_name: Categories
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_slugify_separator: _
      tags_slugify_format: "tag:{slug}"
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - macros
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        light: material/indigo-light
        dark: material/indigo-dark
      interaction:
        enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      locale: en
      timezone: UTC
      enable_git_follow: true
  - glightbox: # https://github.com/blueswen/mkdocs-glightbox#usage
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/thumb-up-outline
        name: Yes - This page was helpful
        data: 1
        note: >-
          Thank you for your feedback! If you have any questions or
          suggestions, please feel free to reach out to us.
      - icon: material/thumb-down-outline
        name: No - This page could be improved
        data: 0
        note: >-
          Thank you for your feedback! If you have any questions or
          suggestions, please feel free to reach out to us.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  social:
    - icon: material/github
      link: https://github.com/ubergoonz/
    - icon: material/linkedin
      link: https://www.linkedin.com/in/ubergoonz/
    - icon: material/gitlab
      link: https://gitlab.com/ubergoonz/
  github_token: !ENV GITHUB_TOKEN
  blog:
    dir: blog
    author: Leslie Wang
    author_image: https://github.com/ubergoonz.png
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true
  tags:
    github-copilot: copilot
    gitlab: gitlab
    markdown: md
    automation: automation
    nix: nix
    plantuml: plantuml
    vscode: vscode

extra_javascript:
  - assets/javascripts/consent.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: ubergoonz
      repo: docs-blog
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs"] # this is needed to make it easier to linking pathsrelative to the mkdocs root
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.caption:

nav:
  - 🏠 Home: 
    - index.md
    - About: about/index.md
    - Navigation: about/navigation.md
    - Site Architecture: about/site-architecture.md
    - Copyright: about/copyright.md
    - Disclaimer: about/disclaimer.md
    - Changelog: about/changelog.md
  - 📚 Docunmentations:
      - documentations/index.md
      - Automation:
        - Overview: documentations/automation/index.md
        - Explanation: documentations/automation/explanation/index.md
        - How to: documentations/automation/how-to/index.md
        - References: documentations/automation/reference/index.md
        - Tutorials: documentations/automation/tutorial/index.md
      - GitHub Copilot:
        - Overview: documentations/github-copilot/index.md
        - Explanation: documentations/github-copilot/explanation/index.md
        - How to: documentations/github-copilot/how-to/index.md
        - References: documentations/github-copilot/reference/index.md
        - Tutorials: documentations/github-copilot/tutorial/index.md
      - Markdown:
        - Overview: documentations/markdown/index.md
        - Explanation: documentations/markdown/explanation/index.md
        - How to: documentations/markdown/how-to/index.md
        - References: documentations/markdown/reference/index.md
        - Tutorials: documentations/markdown/tutorial/index.md
      - GitLab:
        - Overview: documentations/gitlab/index.md
        - Explanation: documentations/gitlab/explanation/index.md
        - How to: documentations/gitlab/how-to/index.md
        - References: documentations/gitlab/reference/index.md
        - Tutorials: documentations/gitlab/tutorial/index.md
      - Material MkDocs:
          - Overview: documentations/material-mkdocs/index.md
          - Explanation: documentations/material-mkdocs/explanation/index.md
          - How to: documentations/material-mkdocs/how-to/index.md
          - References: documentations/material-mkdocs/reference/index.md
          - Tutorials: documentations/material-mkdocs/tutorial/index.md
      - "*nix": 
        - Overview: documentations/nix/index.md
        - Explanation: documentations/nix/explanation/index.md
        - How to: documentations/nix/how-to/index.md
        - References: documentations/nix/reference/index.md
        - Tutorials: documentations/nix/tutorial/index.md
      - PlantUML: 
        - Overview: documentations/plantuml/index.md
        - Explanation: documentations/plantuml/explanation/index.md
        - How to: documentations/plantuml/how-to/index.md
        - References: documentations/plantuml/reference/index.md
        - Tutorials: documentations/plantuml/tutorial/index.md
      - Visual Studio Code: 
        - Overview: documentations/vscode/index.md
        - Explanation: documentations/vscode/explanation/index.md
        - How to: documentations/vscode/how-to/index.md
        - References: documentations/vscode/reference/index.md
        - Tutorials: documentations/vscode/tutorial/index.md
  - 📝 Blog:
      - blog/index.md
      - Tags: blog/tags.md