authors:
  ubergoonz:
    name: Leslie Wang
    description: >-
      Leslie Wang is a software engineer with a passion for open-source
      development and a knack for creating innovative solutions. He enjoys
      exploring new technologies and sharing his knowledge with the community.
    avatar: https://github.com/ubergoonz.png
    url: https://github.com/ubergoonz
    slug: https://github.com/ubergoonz
